#!/usr/bin/perl

use strict;

use JSON;
use File::Slurp;

my $database = "family_test";
my $project_files = [
    { filename => "family.js", contentType => "application/javascript" },
    { filename => "family.html", contentType => "text/html" },
    { filename => "family.css", contentType => "text/css" },
];

# Upload the design document 
my $json_doc = read_file("family.json");
$json_doc =~ s/\s+/ /g;
my $doc = from_json($json_doc);

my $rev = from_json(`curl -s -X GET http://localhost:5984/$database/_design/family`)->{'_rev'};
$doc->{'_rev'} = $rev;

write_file("/tmp/family.json", to_json($doc));
print `curl -X PUT http://localhost:5984/$database/_design/family --data-binary @/tmp/family.json --user josephburnett:Pr1v\@t3`;

foreach ( @$project_files ) {

    my $filename = $_->{'filename'};
    my $contentType = $_->{'contentType'};

    # Get latest revision
    my $rev = from_json(`curl -s -X GET localhost:5984/$database/html`)->{'_rev'};

    # Upload files
    `curl -X PUT localhost:5984/$database/html/$filename?rev=$rev --data-binary \@./$filename -H \"Content-Type: $contentType\"`;

}
